#include <Arduino.h>
#include <M5Unified.h>
#include <math.h>
#include <stdio.h>

// ---------------------------------------------------------------------------
// CoreS3 + Port B DC motor haptic pulse device.
//
// Architecture:
//  - Core 1: FreeRTOS wave task with vTaskDelayUntil (deterministic 1 ms
//            synthesis). Writes LEDC duty only — the 20 kHz PWM carrier itself
//            is generated by the ESP32-S3 LEDC hardware peripheral.
//  - Core 0: Arduino loop — touch, serial commands, live dashboard, telemetry.
//
// Modes:
//  - SQUARE: on/off toggle at 7.83 Hz, 50% duty.
//  - WAVE:   136.1 Hz Ohm + 7.83 Hz ripple, 0.1 Hz breathing envelope.
//
// Power: boots into WAVE and runs with or without a PC. Any 5 V USB-C supply
// or M5 battery module is enough — Serial is optional telemetry only.
//
// What this does NOT do: recreate planetary Schumann resonance, stimulate the
// vagus nerve, or make medical claims. Optional neodymium magnet on the motor
// increases local kinetic/magnetic feel of the vibration; it is not a therapy
// device. Talk to a clinician for anything beyond everyday novelty use.
// ---------------------------------------------------------------------------

static const int MOTOR_PIN = 8;   // Port B pin 1 (G8) on CoreS3
static const int MOTOR_PIN2 = 9;  // Port B pin 2 (G9) - held low
static const float PULSE_HZ = 7.83f;
static const float OHM_HZ = 136.1f;
static const float WAVE_ENVELOPE_HZ = 0.1f;
static const float WAVE_MAX_FRACTION = 0.85f;  // ~869/1023 thermal headroom

// Hardware LEDC: silent carrier offloaded to silicon (CPU only updates duty).
static const int PWM_RES_BITS = 10;           // 0..1023
static const int PWM_MAX_DUTY = (1 << PWM_RES_BITS) - 1;
static const int PWM_CARRIER_HZ = 20000;      // inaudible (prefer over 5 kHz whine)
static const int PWM_CHANNEL = 0;

// Wave task cadence: 1 ms (~7.3 samples/Ohm cycle). The "5 ms" paste aliases.
static const TickType_t WAVE_PERIOD_TICKS = pdMS_TO_TICKS(1);
static const uint32_t SQUARE_HALF_PERIOD_US =
    (uint32_t)((1000000.0f / PULSE_HZ) / 2.0f);

enum PulseMode : uint8_t { MODE_SQUARE = 0, MODE_WAVE = 1 };

// --- Shared state (Core 0 writes controls; Core 1 writes live meters) ---
portMUX_TYPE g_mux = portMUX_INITIALIZER_UNLOCKED;
volatile bool g_running = true;          // auto-start: works on battery / wall USB
volatile PulseMode g_mode = MODE_WAVE;
volatile uint16_t g_powerLevel = PWM_MAX_DUTY;
volatile bool g_restartWave = true;

volatile bool g_motorOn = false;
volatile uint16_t g_liveDuty = 0;
volatile float g_liveEnvelope = 0.0f;
volatile float g_liveOhm = 0.0f;
volatile float g_liveRipple = 0.0f;
volatile uint32_t g_breathCycles = 0;
volatile uint32_t g_pulseCount = 0;
volatile uint32_t g_waveCore = 0;

TaskHandle_t g_waveTask = nullptr;

uint32_t lastTelemetry = 0;
uint32_t lastUiMs = 0;
uint32_t bootMs = 0;
uint32_t runSessionStartMs = 0;
uint32_t runAccumMs = 0;

// UI colors (CoreS3 320x240)
static const int SCREEN_W = 320;
static const uint16_t COL_BG = TFT_BLACK;
static const uint16_t COL_PANEL = 0x1082;
static const uint16_t COL_ACCENT = 0x07FF;
static const uint16_t COL_OK = 0x07E0;
static const uint16_t COL_STOP = 0xF800;
static const uint16_t COL_MUTED = 0x8410;
static const uint16_t COL_TEXT = TFT_WHITE;
static const uint16_t COL_BAR_BG = 0x2104;
static const uint16_t COL_BAR_FILL = 0x05FF;
static const uint16_t COL_BAR_ENV = 0xFFE0;

static inline uint16_t snapU16(volatile uint16_t *p) {
    portENTER_CRITICAL(&g_mux);
    uint16_t v = *p;
    portEXIT_CRITICAL(&g_mux);
    return v;
}

static inline void setMotorDuty(uint16_t duty) {
    if (duty > PWM_MAX_DUTY) duty = PWM_MAX_DUTY;
    ledcWrite(PWM_CHANNEL, duty);
    g_liveDuty = duty;
    g_motorOn = duty > 0;
}

void formatUptime(char *buf, size_t n, uint32_t sec) {
    uint32_t h = sec / 3600UL;
    uint32_t m = (sec % 3600UL) / 60UL;
    uint32_t s = sec % 60UL;
    snprintf(buf, n, "%02lu:%02lu:%02lu", (unsigned long)h, (unsigned long)m,
             (unsigned long)s);
}

uint32_t currentRunMs(uint32_t nowMs) {
    if (!g_running) return runAccumMs;
    return runAccumMs + (nowMs - runSessionStartMs);
}

void drawBar(int x, int y, int w, int h, float frac, uint16_t fill,
             float marker = -1.0f) {
    if (frac < 0.0f) frac = 0.0f;
    if (frac > 1.0f) frac = 1.0f;
    M5.Lcd.fillRect(x, y, w, h, COL_BAR_BG);
    int fw = (int)(frac * w + 0.5f);
    if (fw > 0) M5.Lcd.fillRect(x, y, fw, h, fill);
    M5.Lcd.drawRect(x, y, w, h, COL_MUTED);
    if (marker >= 0.0f) {
        if (marker > 1.0f) marker = 1.0f;
        int mx = x + (int)(marker * (w - 1));
        M5.Lcd.drawFastVLine(mx, y - 1, h + 2, COL_BAR_ENV);
    }
}

void drawDashboard(bool fullRedraw) {
    const uint32_t nowMs = millis();
    const bool running = g_running;
    const bool motorOn = g_motorOn;
    const PulseMode mode = g_mode;
    const uint16_t powerLevel = snapU16(&g_powerLevel);
    const uint16_t liveDuty = snapU16(&g_liveDuty);
    const float liveEnvelope = g_liveEnvelope;
    const float liveOhm = g_liveOhm;
    const float liveRipple = g_liveRipple;
    const uint32_t breathCycles = g_breathCycles;
    const uint32_t pulseCount = g_pulseCount;
    const uint32_t waveCore = g_waveCore;

    const int powerPct = (int)(powerLevel * 100UL / PWM_MAX_DUTY);
    const int dutyPct = (int)(liveDuty * 100UL / PWM_MAX_DUTY);
    char bootUp[16];
    char runUp[16];
    formatUptime(bootUp, sizeof(bootUp), (nowMs - bootMs) / 1000UL);
    formatUptime(runUp, sizeof(runUp), currentRunMs(nowMs) / 1000UL);

    if (fullRedraw) {
        M5.Lcd.fillScreen(COL_BG);
        M5.Lcd.fillRect(0, 0, SCREEN_W, 28, COL_PANEL);
        M5.Lcd.setTextSize(2);
        M5.Lcd.setTextColor(COL_ACCENT, COL_PANEL);
        M5.Lcd.setCursor(6, 6);
        M5.Lcd.print("SCHUMAN S3");
        M5.Lcd.setTextSize(1);
        M5.Lcd.setTextColor(COL_MUTED, COL_BG);
        M5.Lcd.setCursor(6, 226);
        M5.Lcd.print("Tap: start/stop  Serial: START STOP POWER MODE  USB/BAT OK");
    }

    M5.Lcd.fillRoundRect(200, 4, 114, 20, 4,
                         running ? (motorOn ? COL_OK : COL_ACCENT) : COL_STOP);
    M5.Lcd.setTextSize(1);
    M5.Lcd.setTextColor(TFT_BLACK,
                         running ? (motorOn ? COL_OK : COL_ACCENT) : COL_STOP);
    M5.Lcd.setCursor(210, 10);
    if (!running) {
        M5.Lcd.print("  STOPPED  ");
    } else if (mode == MODE_WAVE) {
        M5.Lcd.print(motorOn ? "  EMITTING " : "  SWELLING ");
    } else {
        M5.Lcd.print(motorOn ? "  PULSING  " : "  IDLE GAP ");
    }

    M5.Lcd.fillRect(0, 30, SCREEN_W, 18, COL_BG);
    M5.Lcd.setTextColor(COL_TEXT, COL_BG);
    M5.Lcd.setCursor(6, 34);
    if (mode == MODE_SQUARE) {
        M5.Lcd.printf("MODE SQUARE  Core%lu wave  %.2f Hz @ Port B G8",
                      (unsigned long)waveCore, PULSE_HZ);
    } else {
        M5.Lcd.printf("MODE WAVE    Core%lu LEDC  Ohm+ripple+env @ G8",
                      (unsigned long)waveCore);
    }

    M5.Lcd.fillRect(4, 52, 198, 78, COL_PANEL);
    M5.Lcd.setTextColor(COL_MUTED, COL_PANEL);
    M5.Lcd.setCursor(10, 58);
    M5.Lcd.print("FREQUENCY MATRIX");
    M5.Lcd.setTextColor(COL_TEXT, COL_PANEL);
    M5.Lcd.setCursor(10, 74);
    if (mode == MODE_WAVE) {
        M5.Lcd.printf("Ohm carrier   %6.1f Hz", OHM_HZ);
        M5.Lcd.setCursor(10, 88);
        M5.Lcd.printf("Ripple        %6.2f Hz", PULSE_HZ);
        M5.Lcd.setCursor(10, 102);
        M5.Lcd.printf("Envelope      %6.2f Hz  (6 cpm)", WAVE_ENVELOPE_HZ);
        M5.Lcd.setCursor(10, 116);
        M5.Lcd.printf("PWM carrier   %5d Hz  HW LEDC", PWM_CARRIER_HZ);
    } else {
        M5.Lcd.printf("Pulse         %6.2f Hz", PULSE_HZ);
        M5.Lcd.setCursor(10, 88);
        M5.Lcd.print("Ohm carrier        off");
        M5.Lcd.setCursor(10, 102);
        M5.Lcd.print("Envelope           off");
        M5.Lcd.setCursor(10, 116);
        M5.Lcd.printf("PWM carrier   %5d Hz  HW LEDC", PWM_CARRIER_HZ);
    }

    M5.Lcd.fillRect(206, 52, 110, 78, COL_PANEL);
    M5.Lcd.setTextColor(COL_MUTED, COL_PANEL);
    M5.Lcd.setCursor(212, 58);
    M5.Lcd.print("LIVE SIGNAL");
    M5.Lcd.setTextColor(COL_TEXT, COL_PANEL);
    M5.Lcd.setCursor(212, 74);
    M5.Lcd.printf("Duty  %3d%%", dutyPct);
    drawBar(212, 88, 92, 10, liveDuty / (float)PWM_MAX_DUTY, COL_BAR_FILL,
            mode == MODE_WAVE ? liveEnvelope : -1.0f);
    M5.Lcd.setTextColor(COL_MUTED, COL_PANEL);
    M5.Lcd.setCursor(212, 104);
    M5.Lcd.print("Ohm");
    drawBar(236, 104, 68, 8, (liveOhm * 0.5f) + 0.5f, COL_ACCENT);
    M5.Lcd.setCursor(212, 118);
    M5.Lcd.print("Rip");
    drawBar(236, 118, 68, 8, (liveRipple * 0.5f) + 0.5f, COL_OK);

    M5.Lcd.fillRect(4, 134, 312, 86, COL_PANEL);
    M5.Lcd.setTextColor(COL_MUTED, COL_PANEL);
    M5.Lcd.setCursor(10, 140);
    M5.Lcd.print("ANALYTICS");
    M5.Lcd.setTextColor(COL_TEXT, COL_PANEL);
    M5.Lcd.setCursor(10, 156);
    M5.Lcd.printf("Power limit   %3d%%", powerPct);
    drawBar(120, 156, 180, 10, powerPct / 100.0f, COL_ACCENT);
    M5.Lcd.setCursor(10, 174);
    M5.Lcd.printf("Breath cycles %4lu", (unsigned long)breathCycles);
    M5.Lcd.setCursor(160, 174);
    M5.Lcd.printf("Square pulses %6lu", (unsigned long)pulseCount);
    M5.Lcd.setCursor(10, 192);
    M5.Lcd.printf("Boot uptime   %s", bootUp);
    M5.Lcd.setCursor(160, 192);
    M5.Lcd.printf("Run time  %s", runUp);
    M5.Lcd.setTextColor(COL_MUTED, COL_PANEL);
    M5.Lcd.setCursor(10, 208);
    M5.Lcd.printf("Env %.0f%%  10-bit LEDC  cap %.0f%%  no-PC boot OK",
                  liveEnvelope * 100.0f, WAVE_MAX_FRACTION * 100.0f);
}

void markRunning(bool on) {
    uint32_t now = millis();
    if (on && !g_running) {
        runSessionStartMs = now;
        g_running = true;
        g_restartWave = true;
    } else if (!on && g_running) {
        runAccumMs += now - runSessionStartMs;
        g_running = false;
        setMotorDuty(0);
        g_liveOhm = 0.0f;
        g_liveRipple = 0.0f;
        g_liveEnvelope = 0.0f;
    }
}

// --- Core 1: deterministic waveform synthesis ---
void WaveformTask(void *pvParameters) {
    (void)pvParameters;
    g_waveCore = xPortGetCoreID();
    TickType_t xLastWakeTime = xTaskGetTickCount();
    uint32_t waveStartUs = micros();
    uint32_t lastSquareToggleUs = micros();
    bool squareOn = false;

    for (;;) {
        if (g_restartWave) {
            g_restartWave = false;
            waveStartUs = micros();
            lastSquareToggleUs = waveStartUs;
            squareOn = false;
        }

        if (!g_running) {
            setMotorDuty(0);
            g_liveOhm = 0.0f;
            g_liveRipple = 0.0f;
            g_liveEnvelope = 0.0f;
            vTaskDelayUntil(&xLastWakeTime, WAVE_PERIOD_TICKS);
            continue;
        }

        const PulseMode mode = g_mode;
        const uint16_t powerLevel = snapU16(&g_powerLevel);
        const uint32_t nowUs = micros();

        if (mode == MODE_SQUARE) {
            if (nowUs - lastSquareToggleUs >= SQUARE_HALF_PERIOD_US) {
                lastSquareToggleUs = nowUs;
                squareOn = !squareOn;
                if (squareOn) g_pulseCount++;
            }
            setMotorDuty(squareOn ? powerLevel : 0);
            g_liveOhm = 0.0f;
            g_liveRipple = squareOn ? 1.0f : -1.0f;
            g_liveEnvelope = 1.0f;
        } else {
            float t = (nowUs - waveStartUs) / 1000000.0f;
            float ohm = sinf(2.0f * PI * OHM_HZ * t);
            float ripple = sinf(2.0f * PI * PULSE_HZ * t);
            float envelope = sinf(2.0f * PI * WAVE_ENVELOPE_HZ * t);
            float composite = (ohm + ripple) * 0.5f;
            float normPower = composite * 0.5f + 0.5f;
            float normEnvelope = envelope * 0.5f + 0.5f;
            float dutyF = normPower * normEnvelope * WAVE_MAX_FRACTION *
                          (powerLevel / (float)PWM_MAX_DUTY) * PWM_MAX_DUTY;
            uint16_t duty = (uint16_t)dutyF;
            setMotorDuty(duty);
            g_liveOhm = ohm;
            g_liveRipple = ripple;
            g_liveEnvelope = normEnvelope;
            uint32_t cyclesNow = (uint32_t)(t * WAVE_ENVELOPE_HZ);
            if (cyclesNow > g_breathCycles) g_breathCycles = cyclesNow;
        }

        vTaskDelayUntil(&xLastWakeTime, WAVE_PERIOD_TICKS);
    }
}

void setup() {
    auto cfg = M5.config();
    // Do not wait for a USB host — required for battery / wall-adapter boot.
    cfg.serial_baudrate = 115200;
    M5.begin(cfg);

    pinMode(MOTOR_PIN2, OUTPUT);
    digitalWrite(MOTOR_PIN2, LOW);
    ledcSetup(PWM_CHANNEL, PWM_CARRIER_HZ, PWM_RES_BITS);
    ledcAttachPin(MOTOR_PIN, PWM_CHANNEL);
    ledcWrite(PWM_CHANNEL, 0);

    // Optional USB serial only. Never block if no PC is attached.
    Serial.begin(115200);
    delay(50);

    bootMs = millis();
    runSessionStartMs = bootMs;
    g_running = true;
    g_mode = MODE_WAVE;
    g_restartWave = true;

    drawDashboard(true);
    lastTelemetry = millis();
    lastUiMs = millis();

    // Pin synthesis to Core 1; Core 0 keeps UI/touch/serial responsive.
    xTaskCreatePinnedToCore(WaveformTask, "WaveTask", 4096, nullptr, 2,
                            &g_waveTask, 1);

    Serial.println(
        "{\"status\":\"BOOT\",\"pin\":8,\"ohm_hz\":136.1,\"ripple_hz\":7.83,"
        "\"envelope_hz\":0.1,\"pwm_hz\":20000,\"pwm_bits\":10,\"mode\":\"WAVE\","
        "\"standalone\":true}");
}

void loop() {
    M5.update();

    // Serial control (ignored when no host is connected — motor still runs)
    if (Serial.available() > 0) {
        String cmd = Serial.readStringUntil('\n');
        cmd.trim();
        cmd.toUpperCase();
        if (cmd == "STOP") {
            markRunning(false);
            drawDashboard(true);
        } else if (cmd == "START") {
            markRunning(true);
            drawDashboard(true);
        } else if (cmd == "MODE SQUARE") {
            g_mode = MODE_SQUARE;
            g_restartWave = true;
            drawDashboard(true);
        } else if (cmd == "MODE WAVE") {
            g_mode = MODE_WAVE;
            g_restartWave = true;
            drawDashboard(true);
        } else if (cmd.startsWith("POWER ")) {
            int pct = cmd.substring(6).toInt();
            pct = constrain(pct, 0, 100);
            g_powerLevel = (uint16_t)(pct * PWM_MAX_DUTY / 100);
            drawDashboard(true);
        }
    }

    if (M5.Touch.getCount()) {
        auto t = M5.Touch.getDetail(0);
        if (t.wasPressed()) {
            markRunning(!g_running);
            drawDashboard(true);
        }
    }

    uint32_t nowMs = millis();
    if (nowMs - lastUiMs >= 125) {
        lastUiMs = nowMs;
        drawDashboard(false);
    }

    if (nowMs - lastTelemetry >= 1000) {
        lastTelemetry = nowMs;
        // Best-effort USB telemetry. Motor + UI keep running with no PC attached.
        if (Serial) {
            char bootUp[16];
            char runUp[16];
            formatUptime(bootUp, sizeof(bootUp), (nowMs - bootMs) / 1000UL);
            formatUptime(runUp, sizeof(runUp), currentRunMs(nowMs) / 1000UL);
            const int powerPct =
                (int)(snapU16(&g_powerLevel) * 100UL / PWM_MAX_DUTY);
            const int dutyPct =
                (int)(snapU16(&g_liveDuty) * 100UL / PWM_MAX_DUTY);
            if (g_mode == MODE_SQUARE) {
                Serial.printf(
                    "{\"status\":\"%s\",\"mode\":\"SQUARE\",\"freq_hz\":7.83,"
                    "\"power_pct\":%d,\"duty_pct\":%d,\"pulses\":%lu,"
                    "\"wave_core\":%lu,\"boot_uptime\":\"%s\","
                    "\"run_uptime\":\"%s\",\"uptime_s\":%lu,"
                    "\"standalone\":true}\n",
                    g_running ? "PULSING" : "STOPPED", powerPct, dutyPct,
                    (unsigned long)g_pulseCount, (unsigned long)g_waveCore,
                    bootUp, runUp,
                    (unsigned long)((nowMs - bootMs) / 1000UL));
            } else {
                Serial.printf(
                    "{\"status\":\"%s\",\"mode\":\"WAVE\",\"ohm_hz\":136.1,"
                    "\"ripple_hz\":7.83,\"envelope_hz\":0.1,\"power_pct\":%d,"
                    "\"duty_pct\":%d,\"envelope_pct\":%.0f,"
                    "\"breath_cycles\":%lu,\"wave_core\":%lu,"
                    "\"boot_uptime\":\"%s\",\"run_uptime\":\"%s\","
                    "\"uptime_s\":%lu,\"standalone\":true}\n",
                    g_running ? "PULSING" : "STOPPED", powerPct, dutyPct,
                    g_liveEnvelope * 100.0f, (unsigned long)g_breathCycles,
                    (unsigned long)g_waveCore, bootUp, runUp,
                    (unsigned long)((nowMs - bootMs) / 1000UL));
            }
        }
    }
}
